version: '3.8'

services:
   #databasec section

   #productdb: sqlserver
   productdb:
      image: mcr.microsoft.com/mssql/server:2019-latest
      container_name: productdb
      environment:
         SA_PASSWORD: "Passw0rd!"
         ACCEPT_EULA: "Y"
      restart: always
      volumes:
         - sqlserver_data:/var/lib/sqlserver/data
      ports:
         - "1435:1433"

   #categorydb: mysql
   categorydb:
      image: mysql:8.0.29
      container_name: categorydb
      environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=CategoryDb
       - MYSQL_USER=provider
       - MYSQL_PASSWORD=Passw0rd!
       - MYSQL_ROOT_HOST=127.0.0.1
      restart: always
      volumes:
         - mysql_data:/var/lib/mysql
      ports:
         - "3308:3306"
   
   #customerdb: mongo
   customerdb: 
      image: mongo
      container_name: customerdb
      restart: always
      ports:
         - "27017:27017"
      volumes:
         - mongo_data:/data/db

   basketdb:
      image: postgres:alpine3.16
      container_name: basketdb
      environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=BasketDb
      restart: always
      ports:
         - "5433:5432"
      volumes:
         - postgres_data:/var/lib/postgresql/data

   # pgadmin:
   #     image: dpage/pgadmin4
   #     container_name: pgadmin
   #     environment:
   #      - PGADMIN_DEFAULT_EMAIL=provider
   #      - PGADMIN_DEFAULT_PASSWORD=admin1234
   #     restart: always
   #     ports:
   #      - "5050:80"
   #     volumes:
   #      - pgadmin_data:/root/.pgadmin
         
   portainer:
      image: portainer/portainer-ce
      container_name: portainer
      restart: always
      ports:
         - "8080:8000"
         - "9000:9000"
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - portainer_data:/data

#network section
networks:
  default:
    name: multiple_provider
    driver: bridge

#volumes section
volumes:
  sqlserver_data:
    name: sqlserver_data

  mysql_data:
    name: mysql_data

  portainer_data:
    name: portainer_data

  mongo_data:
    name: mongo_data

  # pgadmin_data:
  #   name: pgadmin_data

  postgres_data:
    name: postgres_data